version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3307"
    volumes:
      - ./.db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lava
  php:
    build: Docker
    image: webforce/php:7.2-fpm
    ports:
      - "81:81"
    volumes:
      - .:/var/www/lava
  nginx:
    image: nginx
    volumes:
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/lava
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
